# Generated by Django 3.0.1 on 2020-01-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0003_auto_20200105_1622'),
        ('pontosTuristicos', '0005_pontoturistico_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='localizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localizacao.Localizacao'),
            preserve_default=False,
        ),
    ]
