# Generated by Django 3.0.1 on 2020-01-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='latitude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='localizacao',
            name='longitude',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
